publishDir: docs
theme: Blogpaper
title: Title # Your site title
author:
  name: Ryan # Your name
baseURL: https://example.com # Hostname (and path) to the root, e.g. https://bep.is/
copyright: # Optional, will be displayed on site's footer, if this line is removed an default copyright will be generated
languageCode: en # The language code of your site, by default "en"
menu:
  main: # Optional, the menu to display on top-right of your site, see https://gohugo.io/templates/menu-templates/#site-config-menus
    - name: About
      url: /about
params:
  description: This is a new website # The description of your site (used on a <meta> tag)
  subtitleLength: 25 # The number of words on the subtitle of a page